//
//  AuthViewController.swift
//  iHAQ
//
//  Created by Evgeny Ivanov on 25.06.2020.
//  Copyright (c) 2020 r9g. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Spring

class AuthViewController: UIViewController {

    // MARK: Object lifecycle

    @IBOutlet var loginTextfield: UITextField!
    @IBOutlet var passwordTextfield: UITextField!
    @IBOutlet var loginButton: UIButton!
    @IBOutlet var registrateBUtton: UIButton!

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {

    }
    @IBAction func loginTap(_ sender: Any) {
    }
    @IBAction func registrateTap(_ sender: Any) {
    }
    
    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        
    }

    // MARK: Actions

}
